version: '3.8'
services:
  kde-dev:
    build:
      context: .
      dockerfile: Dockerfile
    user: admin
    shm_size: '16gb'
    pid: 'host'
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
